SourceCode/Sheng.WeixinConstruction.Management.Shell/Models/Settings/AuthorizationCallbackDemoViewModel.cs
/*
********************************************************************
*
*    曹旭升（sheng.c）
*    E-mail: cao.silhouette@msn.com
*    QQ: 279060597
*    https://github.com/iccb1013
*    http://shengxunwei.com
*
*    © Copyright 2016
*
********************************************************************/


using Sheng.WeixinConstruction.WeixinContract.ThirdParty;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Sheng.WeixinConstruction.Management.Shell.Models
{
    public class AuthorizationCallbackDemoViewModel
    {
        public WeixinThirdPartyAuthorizationInfo Info
        {
            get;
            set;
        }
    }
}

SourceCode/Sheng.WeixinConstruction.Management.Shell/Areas/Api/Controllers/AdvancedArticleController.cs
/*
********************************************************************
*
*    曹旭升（sheng.c）
*    E-mail: cao.silhouette@msn.com
*    QQ: 279060597
*    https://github.com/iccb1013
*    http://shengxunwei.com
*
*    © Copyright 2016
*
********************************************************************/


using Sheng.WeixinConstruction.Core;
using Sheng.WeixinConstruction.Infrastructure;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sheng.WeixinConstruction.Management.Shell.Areas.Api.Controllers
{
    public class AdvancedArticleController : BasalController
    {
        private static readonly DomainManager _domainManager = DomainManager.Instance;
        private static readonly AdvancedArticleManager _advancedArticleManager = AdvancedArticleManager.Instance;
        private static readonly OperatedLogManager _operatedLogManager = OperatedLogManager.Instance;

        public ActionResult CreateAdvancedArticle()
        {
            AdvancedArticleEntity advancedArticle = RequestArgs<AdvancedArticleEntity>();
            if (advancedArticle == null)
            {
                return RespondResult(false, "参数无效。");
            }

            advancedArticle.Domain = UserContext.User.Domain;
            advancedArticle.AppId = DomainContext.AppId;
            advancedArticle.CreateUser = UserContext.User.Id;
            _advancedArticleManager.CreateAdvancedArticle(advancedArticle);

            #region 操作日志

            _operatedLogManager.Create(new OperatedLogEntity()
            {
                Domain = DomainContext.Domain.Id,
                AppId = DomainContext.AppId,
                User = UserContext.User.Id,
                IP = Request.UserHostAddress,
                Module = EnumModule.AdvancedArticle,
                Description = "创建高级图文"
            });

            #endregion

            return RespondResult();
        }

        public ActionResult UpdateAdvancedArticle()
        {
            AdvancedArticleEntity advancedArticle = RequestArgs<AdvancedArticleEntity>();
            if (advancedArticle == null)
            {
                return RespondResult(false, "参数无效。");
            }

            advancedArticle.Domain = UserContext.User.Domain;
            advancedArticle.AppId = DomainContext.AppId;
            _advancedArticleManager.UpdateAdvancedArticle(advancedArticle);

            #region 操作日志

            _operatedLogManager.Create(new OperatedLogEntity()
            {
                Domain = DomainContext.Domain.Id,
                AppId = DomainContext.AppId,
                User = UserContext.User.Id,
                IP = Request.UserHostAddress,
                Module = EnumModule.AdvancedArticle,
                Description = "更新增强图文"
            });

            #endregion

            return RespondResult();
        }

        public ActionResult RemoveAdvancedArticle()
        {
            string id = Request.QueryString["id"];

            if (String.IsNullOrEmpty(id))
            {
                return RespondResult(false, "参数无效。");
            }

            _advancedArticleManager.RemoveAdvancedArticle(Guid.Parse(id));

            #region 操作日志

            _operatedLogManager.Create(new OperatedLogEntity()
            {
                Domain = DomainContext.Domain.Id,
                AppId = DomainContext.AppId,
                User = UserContext.User.Id,
                IP = Request.UserHostAddress,
                Module = EnumModule.AdvancedArticle,
                Description = "删除增强图文件"
            });

            #endregion

            return RespondResult();
        }

        public ActionResult GetAdvancedArticle()
        {
            string id = Request.QueryString["id"];

            if (String.IsNullOrEmpty(id))
            {
                return RespondResult(false, "参数无效。");
            }

            AdvancedArticleEntity advancedArticle = _advancedArticleManager.GetAdvancedArticle(Guid.Parse(id));

            return RespondDataResult(advancedArticle);
        }

        public ActionResult GetAdvancedArticleList()
        {
            GetItemListArgs args = RequestArgs<GetItemListArgs>();
            if (args == null)
            {
                return RespondResult(false, "参数无效。");
            }

            args.DomainId = UserContext.User.Domain;
            args.AppId = DomainContext.AppId;

            GetItemListResult result = _advancedArticleManager.GetAdvancedArticleList(args);
            return RespondDataResult(result);
        }


    }
}

SourceCode/Sheng.WeixinConstruction.Management.Shell/Areas/Api/Controllers/AdvertisingController.cs
/*
********************************************************************
*
*    曹旭升（sheng.c）
*    E-mail: cao.silhouette@msn.com
*    QQ: 279060597
*    https://github.com/iccb1013
*    http://shengxunwei.com
*
*    © Copyright 2016
*
********************************************************************/


using Sheng.WeixinConstruction.Core;
using Sheng.WeixinConstruction.Infrastructure;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sheng.WeixinConstruction.Management.Shell.Areas.Api.Controllers
{
    public class AdvertisingController : BasalController
    {
        private static readonly DomainManager _domainManager = DomainManager.Instance;
        private static readonly AdvertisingManager _advertisingManager = AdvertisingManager.Instance;
        private static readonly OperatedLogManager _operatedLogManager = OperatedLogManager.Instance;

        public ActionResult CreateAdvertising()
        {
            AdvertisingEntity advertising = RequestArgs<AdvertisingEntity>();
            if (advertising == null)
            {
                return RespondResult(false, "参数无效。");
            }

            advertising.Domain = UserContext.User.Domain;
            advertising.AppId = DomainContext.AppId;
            advertising.CreateUser = UserContext.User.Id;
            _advertisingManager.CreateAdvertising(advertising);

            #region 操作日志

            _operatedLogManager.Create(new OperatedLogEntity()
            {
                Domain = DomainContext.Domain.Id,
                AppId = DomainContext.AppId,
                User = UserContext.User.Id,
                IP = Request.UserHostAddress,
                Module = EnumModule.Settings,
                Description = "创建广告"
            });

            #endregion

            return RespondResult();
        }

        public ActionResult UpdateAdvertising()
        {
            AdvertisingEntity advertising = RequestArgs<AdvertisingEntity>();
            if (advertising == null)
            {
                return RespondResult(false, "参数无效。");
            }

            advertising.Domain = UserContext.User.Domain;
            advertising.AppId = DomainContext.AppId;
            _advertisingManager.UpdateAdvertising(advertising);

            #region 操作日志

            _operatedLogManager.Create(new OperatedLogEntity()
            {
                Domain = DomainContext.Domain.Id,
                AppId = DomainContext.AppId,
                User = UserContext.User.Id,
                IP = Request.UserHostAddress,
                Module = EnumModule.Settings,
                Description = "更新广告"
            });

            #endregion

            return RespondResult();
        }

        public ActionResult RemoveAdvertising()
        {
            string id = Request.QueryString["id"];

            if (String.IsNullOrEmpty(id))
            {
                return RespondResult(false, "参数无效。");
            }

            _advertisingManager.RemoveAdvertising(Guid.Parse(id));

            #region 操作日志

            _operatedLogManager.Create(new OperatedLogEntity()
            {
                Domain = DomainContext.Domain.Id,
                AppId = DomainContext.AppId,
                User = UserContext.User.Id,
                IP = Request.UserHostAddress,
                Module = EnumModule.Settings,
                Description = "删除广告"
            });

            #endregion

            return RespondResult();
        }

        public ActionResult GetAdvertising()
        {
            string id = Request.QueryString["id"];

            if (String.IsNullOrEmpty(id))
            {
                return RespondResult(false, "参数无效。");
            }

            AdvertisingEntity advertising = _advertisingManager.GetAdvertising(Guid.Parse(id));

            return RespondDataResult(advertising);
        }

        public ActionResult GetAdvertisingList()
        {
            GetGetAdvertisingListArgs args = RequestArgs<GetGetAdvertisingListArgs>();
            if (args == null)
            {
                return RespondResult(false, "参数无效。");
            }

            args.DomainId = UserContext.User.Domain;
            args.AppId = DomainContext.AppId;

            GetItemListResult result = _advertisingManager.GetAdvertisingList(args);
            return RespondDataResult(result);
        }
    }
}

SourceCode/Sheng.WeixinConstruction.Management.Shell/Controllers/MemberController.cs
/*
********************************************************************
*
*    曹旭升（sheng.c）
*    E-mail: cao.silhouette@msn.com
*    QQ: 279060597
*    https://github.com/iccb1013
*    http://shengxunwei.com
*
*    © Copyright 2016
*
********************************************************************/


using Sheng.WeixinConstruction.Core;
using Sheng.WeixinConstruction.Infrastructure;
using Sheng.WeixinConstruction.Management.Shell.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sheng.WeixinConstruction.Management.Shell.Controllers
{
    public class MemberController : BasalController
    {
        private static readonly MemberManager _memberManager = MemberManager.Instance;
        private static readonly MemberGroupManager _memberGroupManager = MemberGroupManager.Instance;
        private static readonly GroupMessageManager _groupMessageManager = GroupMessageManager.Instance;
        private static readonly CouponManager _couponManager = CouponManager.Instance;
        private static readonly PointCommodityManager _pointCommodityManager = PointCommodityManager.Instance;
        private static readonly RecommendUrlManager _recommendUrlManager = RecommendUrlManager.Instance;


        #region 会员管理

        public ActionResult Member()
        {
            //GetMaterialListArgs args = new GetMaterialListArgs();
            //args.Type = MaterialType.Image;
            //args.Count = 20;
            //args.Offset = 0;
            //RequestApiResult<GetNormalMaterialListResult> r = MaterialApiWrapper.GetNormalMaterialList(this.DomainContext, args);

            MemberViewModel model = new MemberViewModel();
            model.DomainContext = this.DomainContext;
            return View(model);
        }

        public ActionResult MemberInfo()
        {
            string strId = Request.QueryString["id"];
            Guid id = Guid.Empty;
            if (String.IsNullOrEmpty(strId) || Guid.TryParse(strId, out id) == false)
            {
                //TODO:ID无效
                //return RedirectToAction("PointCommodity", new { domain = domain });
            }

            MemberInfoViewModel model = new MemberInfoViewModel();
            model.MemberCardLevelList = _memberManager.GetMemberCardList(DomainContext.Domain.Id, DomainContext.AppId);
            model.Member = _memberManager.GetMember(id);
            if (model.Member.CardLevel.HasValue)
            {
                model.MemberCard = _memberManager.GetMemberCard(model.Member.CardLevel.Value);
            }
            else
            {
                SettingsEntity settings = DomainContext.Settings;
                if (settings != null && settings.DefaultMemberCardLevel.HasValue)
                {
                    model.MemberCard = _memberManager.GetMemberCard(settings.DefaultMemberCardLevel.Value);
                }
            }
            return View(model);
        }

        public ActionResult MemberGroupEdit()
        {
            return View();
        }

        public ActionResult MemberSelect()
        {
            return View();
        }

        #endregion

        #region 消息群发

        /// <summary>
        /// 群发功能
        /// </summary>
        /// <returns></returns>
        public ActionResult GroupMessage()
        {
            MemberGroupMessageViewModel model = new MemberGroupMessageViewModel();
            model.MemberGroupList = _memberGroupManager.GetMemberGroupList(DomainContext.Domain.Id,DomainContext.AppId);
            return View(model);
        }

        public ActionResult SentGroupMessage()
        {
            return View();
        }

        public ActionResult GroupMessageDetail()
        {
            string strId = Request.QueryString["id"];
            Guid id = Guid.Empty;
            if (String.IsNullOrEmpty(strId) || Guid.TryParse(strId, out id) == false)
            {
                //TODO:ID无效
                //return RedirectToAction("PointCommodity", new { domain = domain });
            }

            GroupMessageDetailViewModel model = new GroupMessageDetailViewModel();
            model.GroupMessage = _groupMessageManager.GetGroupMessage(id);
            return View(model);
        }

        #endregion

        #region 积分商品

        public ActionResult PointCommodity()
        {
            //PointCommodityViewModel model = new PointCommodityViewModel();
            return View();
        }

        public ActionResult PointCommodityEdit()
        {
            return View();
        }

        /// <summary>
        /// 订单列表
        /// </summary>
        /// <returns></returns>
        public ActionResult PointCommodityOrder()
        {
            return View();
        }

        public ActionResult PointCommodityOrderDetail()
        {
            string strId = Request.QueryString["id"];
            Guid id = Guid.Empty;
            if (String.IsNullOrEmpty(strId) || Guid.TryParse(strId, out id) == false)
            {
                //TODO:ID无效
                //return RedirectToAction("PointCommodity", new { domain = domain });
            }

            PointCommodityOrderDetailViewModel model = new PointCommodityOrderDetailViewModel();
            model.Order = _pointCommodityManager.GetOrder(id);
            model.Member = _memberManager.GetMember(model.Order.Member);
            model.ItemList = _pointCommodityManager.GetOrderItemList(id);
            model.LogList = _pointCommodityManager.GetOrderLogList(id);
            return View(model);
        }

        #endregion

        #region 卡券

        public ActionResult Coupon()
        {
            return View();
        }

        public ActionResult CouponEdit()
        {
            return View();
        }

        /// <summary>
        /// 已派发卡券列表
        /// </summary>
        /// <returns></returns>
        public ActionResult DistributedCoupon()
        {
            string strCouponId = Request.QueryString["couponId"];
            Guid couponId = Guid.Empty;
            if (String.IsNullOrEmpty(strCouponId) || Guid.TryParse(strCouponId, out couponId) == false)
            {
                //TODO:ID无效
                //return RedirectToAction("PointCommodity", new { domain = domain });
            }

            DistributedCouponViewModel model = new DistributedCouponViewModel();
            model.Coupon = _couponManager.GetCoupon(couponId);
            return View(model);
        }

        /// <summary>
        /// 派发卡券
        /// </summary>
        /// <returns></returns>
        public ActionResult CouponDistribute()
        {
            string strCouponId = Request.QueryString["couponId"];
            Guid couponId = Guid.Empty;
            if (String.IsNullOrEmpty(strCouponId) || Guid.TryParse(strCouponId, out couponId) == false)
            {
                //TODO:ID无效
                //return RedirectToAction("PointCommodity", new { domain = domain });
            }

            CouponEntity coupon = _couponManager.GetCoupon(couponId);
            return View(coupon);
        }

        #endregion

        #region 多级推广

        public ActionResult RecommendUrl()
        {
            //没有绑定公众号的，初始化一个临时的设置对象用于UI显示
            //此时UI是不允许编辑的
            RecommendUrlSettingsEntity settings;
            if (DomainContext.Online)
            {
                settings = _recommendUrlManager.GetSettings(DomainContext.Domain.Id, DomainContext.AppId);
            }
            else
            {
                settings = new RecommendUrlSettingsEntity();
            }
            
            return View(settings);
        }

        #endregion
    }
}

SourceCode/Sheng.WeixinConstruction.Management.Shell/Views/Settings/AuthorizationCallbackDemo.cshtml
@model Sheng.WeixinConstruction.Management.Shell.Models.AuthorizationCallbackDemoViewModel

@{
    Layout = null;
}


<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/common")

    @Scripts.Render("~/Scripts/jquery-1.10.2.min.js")
    @Scripts.Render("~/Scripts/layer/layer.js")

    <script type="text/javascript">

    </script>

</head>
<body>
    <div id="divTopBar">
        <div id="divLogo">
            <span class="font_white_22">升讯威 微信营销系统</span>
        </div>
        <div id="divMainMenu">
            <table id="tableTopBar" border="0" cellspacing="0" cellpadding="0">
                <tr>
                    <td class="td_MainMenu @if(ViewBag.MainMenu == "Portal"){@Html.Raw("td_MainMenu_active")}">
                        @Html.ActionLink("管理", "Member", "Member", null, new { @class = "a_white_18" })
                    </td>
                    <td class="td_MainMenu @if(ViewBag.MainMenu == "Campaign"){@Html.Raw("td_MainMenu_active")}">
                        @Html.ActionLink("活动", "Index", "Campaign", null, new { @class = "a_white_18" })
                    </td>
                    <td class="td_MainMenu @if(ViewBag.MainMenu == "Settings"){@Html.Raw("td_MainMenu_active")}">
                        @Html.ActionLink("设置", "Base", "Settings", null, new { @class = "a_white_18" })
                    </td>
                    <td class="td_MainMenu">&nbsp;</td>
                </tr>
            </table>
        </div>
        <div id="divTopRight">
            <table id="tableTopBar" border="0" cellspacing="0" cellpadding="0">
                <tr>
                    <td class="td_MainMenu font_darkBlue_18">UserName</td>
                    <td class="td_MainMenu">@Html.ActionLink("退出", "Logout", "Home", null, new { @class = "a_white_18" })</td>
                </tr>
            </table>
        </div>
    </div>
    <div id="divContainer">
        <div id="divLeftMenu">
            <div id="divLeftTitle">
            </div>
            <div>
                @Html.Partial("_LeftMenu")
            </div>
        </div>
        <div id="divContentWrapper">
            <div id="divContent">
                <div id="divDockingInfo">
                    <div style=" margin-top:20px; margin-left:10px; margin-right:10px; line-height:180%;" class="font_black_14">
                        注意：这是演示画面，可测试授权流程，但并无实际功能。<br />
                        注意：原微信后台中设置的菜单及自动回复都已失效，请在本系统中重新设置。若要修改您的公众号信息，请登陆微信后台修改后，点击"刷新"按钮。<br>

                    </div>
                    <div style=" margin-top:15px;">
                        <div style="float:right">
                            <input name="btnSave" type="button" class="btn_blue" id="btnStep2Next" value="刷 新" />
                        </div>
                        <div style="clear:both"></div>
                    </div>

                    <div style="margin-top:20px;" class="font_black_14">
                        <table width="100%" border cellpadding="5" cellspacing=0 bordercolor="#E0E0E0" rules=rows>
                            <tr bordercolor="#E0E0E0">
                                <td width="5" valign="middle" bgcolor="#EEEEEE">&nbsp;</td>
                                <td width="120" height="26" valign="middle" bgcolor="#EEEEEE">公开信息</td>
                                <td valign="middle" bgcolor="#EEEEEE">&nbsp;</td>
                            </tr>
                            <tr bordercolor="#E0E0E0">
                                <td valign="middle">&nbsp;</td>
                                <td height="26" valign="middle">AppId</td>
                                <td valign="middle">@Model.Info.AppId</td>
                            </tr>
                            <tr bordercolor="#E0E0E0">
                                <td valign="middle">&nbsp;</td>
                                <td height="26" valign="middle">AccessToken</td>
                                <td valign="middle">@Model.Info.AccessToken</td>
                            </tr>
                            <tr bordercolor="#E0E0E0">
                                <td valign="middle">&nbsp;</td>
                                <td height="26" valign="middle">ExpiresIn</td>
                                <td valign="middle">@Model.Info.ExpiresIn</td>
                            </tr>
                            <tr bordercolor="#E0E0E0">
                                <td valign="middle">&nbsp;</td>
                                <td height="26" valign="middle">RefreshToken</td>
                                <td valign="middle">@Model.Info.RefreshToken</td>
                            </tr>
                        </table>
                    </div>


                </div>
            </div>
        </div>
        <div id="divContentMask" style="display:none">
        </div>
    </div>
</body>

</html>

SourceCode/Sheng.WeixinConstruction.Management.Shell/Views/Settings/AutoReplyText.cshtml
@{
    ViewBag.Title = "AutoReplyText";
    Layout = "~/Views/Shared/_LayoutBlank.cshtml";
}


<script>

    var _validator;

    $(document).ready(function ()
    {
        _validator = $("#form").validate({
            onfocusout: false,
            onkeyup: false,
            showErrors: showValidationErrors,
            rules: {
                "txtText": "required"
            },
            messages: {
                "txtText": "请输入回复文字；"
            }
        });
    });

    function save()
    {
        if (_validator.form() == false)
        {
            return;
        }

        var index = parent.layer.getFrameIndex(window.name);
       
        parent.insertReplyTextContent($("#txtText").val(), index);
    }

    function cancel()
    {
        var index = parent.layer.getFrameIndex(window.name); //先得到当前iframe层的索引
        parent.layer.close(index); //再执行关闭
    }
</script>


<div style="margin-left:20px; margin-right:20px; margin-top:20px;">
    <span id="spanTitle" class="font_black_24">回复文字</span>
</div>

<div style=" background-color:#ccc; margin-left:20px; margin-right:20px; margin-top:10px; height:1px;">

</div>

<div style=" position:absolute; overflow:auto ;margin-top:25px;left:30px; right:30px; bottom:60px; top:50px; ">

    <form id="form">
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
                <td>
                    <textarea name="txtText" rows="6" class="input_18" id="txtText" maxlength="300"></textarea>
                </td>
            </tr>

        </table>


    </form>

</div>

<div style=" background-color:#ccc; position:absolute; bottom:55px; left:20px;right:20px; height:1px;">

</div>

<div style="position:absolute; bottom:15px; left:20px;right:20px;">

    <!--
            <div style="float:left;">
                <input name="btnSave" type="button" class="btn_red" id="btnSave" value="删 除" />
            </div>-->

    <div style="float:right">
        <input name="btnSave" type="button" class="btn_blue" id="btnSave" value="保 存" onclick="save()" />
        <input name="btnCancel" type="button" class="btn_blue" id="btnCancel" value="取 消" onclick="cancel()" />
    </div>
    <div style="clear:both">
    </div>
</div>

SourceCode/Sheng.WeixinConstruction.Management.Shell/Views/Settings/DockingDemo.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/common")

    @Scripts.Render("~/Scripts/jquery-1.10.2.min.js")
    @Scripts.Render("~/Scripts/layer/layer.js")

    <script type="text/javascript">

        function docking()
        {
            var loadLayerIndex = layer.load(0, {
                shade: [0.2, '#fff']
            });

            $.ajax({
                url: "/Api/Settings/GetPreAuthCode",
                type: "POST",
                dataType: "json",
                success: function (data, status, jqXHR)
                {
                    if (data.Success)
                    {
                        var url = String.format("https://mp.weixin.qq.com/cgi-bin/componentloginpage?component_appid={0}&pre_auth_code={1}&redirect_uri={2}",
                            data.Data.AppId, data.Data.PreAuthCode, "http://wxcm.shengxunwei.com/Settings/AuthorizationCallbackDemo");
                        window.location.href = url;

                    } else
                    {
                        layer.close(loadLayerIndex);
                        layerAlert(data.Message);
                    }
                },
                error: function (xmlHttpRequest)
                {
                    layer.close(loadLayerIndex);
                    alert("Error: " + xmlHttpRequest.status);
                }
            });
        }


    </script>

</head>
<body>
    <div id="divTopBar">
        <div id="divLogo">
            <span class="font_white_22">升讯威 微信营销系统</span>
        </div>
        <div id="divMainMenu">
            <table id="tableTopBar" border="0" cellspacing="0" cellpadding="0">
                <tr>
                    <td class="td_MainMenu @if(ViewBag.MainMenu == "Portal"){@Html.Raw("td_MainMenu_active")}">
                        @Html.ActionLink("管理", "Member", "Member", null, new { @class = "a_white_18" })
                    </td>
                    <td class="td_MainMenu @if(ViewBag.MainMenu == "Campaign"){@Html.Raw("td_MainMenu_active")}">
                        @Html.ActionLink("活动", "Index", "Campaign", null, new { @class = "a_white_18" })
                    </td>
                    <td class="td_MainMenu @if(ViewBag.MainMenu == "Settings"){@Html.Raw("td_MainMenu_active")}">
                        @Html.ActionLink("设置", "Base", "Settings", null, new { @class = "a_white_18" })
                    </td>
                    <td class="td_MainMenu">&nbsp;</td>
                </tr>
            </table>
        </div>
        <div id="divTopRight">
            <table id="tableTopBar" border="0" cellspacing="0" cellpadding="0">
                <tr>
                    <td class="td_MainMenu font_darkBlue_18">UserName</td>
                    <td class="td_MainMenu">@Html.ActionLink("退出", "Logout", "Home", null, new { @class = "a_white_18" })</td>
                </tr>
            </table>
        </div>
    </div>
    <div id="divContainer">
        <div id="divLeftMenu">
            <div id="divLeftTitle">
            </div>
            <div>
                @Html.Partial("_LeftMenu")
            </div>
        </div>
        <div id="divContentWrapper">
            <div id="divContent">
                <div id="divStartDocking">
                    <div style=" margin-top:20px; margin-left:10px; margin-right:10px; line-height:180%;" class="font_black_14">
                        注意：这是演示画面，可测试授权流程，但并无实际功能。<br />
                        请首先确保您的公众号是 <b>经过微信认证的服务号</b>，才能在对接后正常使用全部功能。<br>
                        如果还没有微信公众号，请前往微信公众平台(<a href="https://mp.weixin.qq.com/" target="_blank">mp.weixin.qq.com</a>)进行注册。
                    </div>

                    <div style="margin-top:20px; background-color:#F6F6F6; padding-top:25px; padding-bottom:25px;">
                        <table width="100%" border="0" cellspacing="0" cellpadding="0">
                            <tr>
                                <td height="120" align="center"><img src="/Content/Images/docking_ico1.gif" width="98" height="98"></td>
                                <td align="center"><img src="/Content/Images/docking_ico2.gif" width="98" height="98"></td>
                                <td align="center"><img src="/Content/Images/docking_ico3.gif" width="98" height="98"></td>
                            </tr>
                            <tr>
                                <td height="40" align="center" class="font_black_24">微信官方许可</td>
                                <td align="center" class="font_black_24">公众号免繁琐设置</td>
                                <td align="center" class="font_black_24">安全可靠</td>
                            </tr>
                            <tr>
                                <td height="30" align="center" class="font_gray_15">腾讯公司审核认证的可靠平台</td>
                                <td align="center" class="font_gray_15">一键对接，轻松快捷</td>
                                <td align="center" class="font_gray_15">本系统不会也无法获取您的密码</td>
                            </tr>
                        </table>
                    </div>

                    <div align="center" style="margin-top:30px;">
                        <img src="/Content/Images/docking_btn.jpg" width="367" height="62" onclick="docking()" style="cursor:pointer">
                    </div>

                </div>
            </div>
        </div>
        <div id="divContentMask" style="display:none">
        </div>
    </div>
</body>

</html>